### PR TITLE
Fix #102: fix chart width issue affecting page width

### PR DESCRIPTION
**Pull request by spasovski**
Pretty straight forward.

### CODE REVIEW

**Comment by spasovski** [comment]
Why does this keep failing?

**Comment by openjck** [comment]
Fixed. The test was failing because the Docker image was unavailable for reasons beyond our control.

**Comment by openjck** [comment]
Just FYI if a pull request title starts with "Fix #[number]" it will automatically close that issue when it's merged. It took me a second to remember which issue this was related to. :smile:

**Comment by openjck** [comment]
I like this! I do find it a little hard to read. Maybe `justify-content: start` (fixing the "hanging indent" issue along with it) and `line-height: 2`?

**Pull request closed without merging**
