### PR TITLE
Add "npm audit" after tests, fix errors

### PR DESCRIPTION
**Pull request by openjck**
This commit also switches the project from Yarn to NPM. NPM has
lockfiles now, which was one of the primary benefits of using Yarn, and
Yarn does not currently have an "audit" command. It plans to add one,
but even then, it's unclear that it will add an "npm audit fix" command
which is incredibly useful.

### CODE REVIEW

**Comment by openjck** [comment]
I don't feel greaaaaaat about switching away from Yarn, given that it's what create-react-app recommends. I read [this bug](https://github.com/yarnpkg/yarn/issues/5808) as saying Yarn would never have a *yarn audit fix* command, which is sort of a deal-breaker, but if I asked for clarification just in case.

**Comment by robhudson** [comment]
So this outputs an audit of the dependencies locally? Does Renovate not cover this already? Or should we include this in CircleCI also -- although maybe it shouldn't block merges.

**Comment by openjck** [comment]
> So this outputs an audit of the dependencies locally?

Yep, exactly.

> Does Renovate not cover this already?

Nope. Renovate updates our direct dependencies, but `npm audit fix` can update sub-dependencies with security vulnerabilities. Also, we have Renovate configured to update packages once per week to cut down on noise and there's no way to make Renovate open pull requests immediately for security vulnerabilities. I opened https://github.com/renovateapp/renovate/issues/1567 about that.

> Or should we include this in CircleCI also -- although maybe it shouldn't block merges.

Yeah, I would love to include this in CircleCI along with all other tests. I agree it shouldn't return a failure because in some cases you can't actually do much or anything about vulnerable sub-dependencies. Right now, `npm run posttest` returns success no matter what.

**Comment by robhudson** [comment]
All sounds good to me.

**Comment by openjck** [comment]
Any reservations, @spasovski?

**Comment by openjck** [comment]
I'm gonna go ahead and merge because a merge conflict would be a bummer, but if we want to change it later I'd be happy to.

**Pull request merged**
